# Use an official PHP image with Apache
FROM php:8.1-apache

# Copy the directory of files into the container at /var/www/html
COPY ./apache/* /var/www/html/

RUN docker-php-ext-install pdo_mysql

# Expose port 80 for the Apache web server
EXPOSE 80